export const collectionType = {
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILIURE: "FETCH_COLLECTIONS_FAILIURE",
  FETCH_COLLECTIONS_REQUEST: "FETCH_COLLECTIONS_REQUEST",
};
